(in-package :gae)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (j:jimport |com.google.appengine.api.datastore.DatastoreServiceFactory|)
  (j:jimport |com.google.appengine.api.datastore.DataTypeTranslator|)
  (j:jimport |com.google.appengine.api.datastore.DataTypeTranslator$ComparableByteArray|)
  (j:jimport |com.google.appengine.api.datastore.DataTypeUtils|)
  (j:jimport |com.google.appengine.api.datastore.Entity|)
  (j:jimport |com.google.appengine.api.datastore.EntityTranslator|)
  (j:jimport |com.google.appengine.api.datastore.FetchOptions|)
  (j:jimport |com.google.appengine.api.datastore.FetchOptions$Builder|)
  (j:jimport |com.google.appengine.api.datastore.Key|)
  (j:jimport |com.google.appengine.api.datastore.KeyFactory|)
  (j:jimport |com.google.appengine.api.datastore.KeyFactory$Builder|)
  (j:jimport |com.google.appengine.api.datastore.Link|)
  (j:jimport |com.google.appengine.api.datastore.Query|)
  (j:jimport |com.google.appengine.api.datastore.Query$FilterPredicate|)
  (j:jimport |com.google.appengine.api.datastore.Query$SortPredicate|)
  (j:jimport |com.google.appengine.api.datastore.ShortBlob|)
  (j:jimport |com.google.appengine.api.datastore.Text|))
